
CREATE TABLE tenants (
  id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
  name NVARCHAR(200) NOT NULL,
  domain NVARCHAR(200) NULL,
  created_at DATETIME2 DEFAULT SYSUTCDATETIME()
);

CREATE TABLE users (
  id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
  tenant_id UNIQUEIDENTIFIER NOT NULL,
  upn NVARCHAR(255) NOT NULL,
  display_name NVARCHAR(255) NULL,
  email NVARCHAR(255) NULL,
  created_at DATETIME2 DEFAULT SYSUTCDATETIME(),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

CREATE TABLE okrs (
  id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
  tenant_id UNIQUEIDENTIFIER NOT NULL,
  owner_user_id UNIQUEIDENTIFIER NULL,
  objective NVARCHAR(1000) NOT NULL,
  from_date DATE NOT NULL,
  to_date DATE NOT NULL,
  status NVARCHAR(30) DEFAULT 'draft',
  created_at DATETIME2 DEFAULT SYSUTCDATETIME(),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  FOREIGN KEY (owner_user_id) REFERENCES users(id)
);

CREATE TABLE key_results (
  id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
  okr_id UNIQUEIDENTIFIER NOT NULL,
  title NVARCHAR(1000) NOT NULL,
  metric_name NVARCHAR(255) NULL,
  target_value DECIMAL(18,4) NULL,
  current_value DECIMAL(18,4) NULL,
  unit NVARCHAR(50) NULL,
  owner_user_id UNIQUEIDENTIFIER NULL,
  status NVARCHAR(30) DEFAULT 'planned',
  FOREIGN KEY (okr_id) REFERENCES okrs(id),
  FOREIGN KEY (owner_user_id) REFERENCES users(id)
);

CREATE TABLE checkins (
  id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
  key_result_id UNIQUEIDENTIFIER NOT NULL,
  checkin_date DATE NOT NULL,
  value DECIMAL(18,4) NOT NULL,
  note NVARCHAR(1000) NULL,
  created_at DATETIME2 DEFAULT SYSUTCDATETIME(),
  FOREIGN KEY (key_result_id) REFERENCES key_results(id)
);
